### ISSUE TITLE
Update README.md

### ISSUE THREAD

**Issue by JohannesHeidecke** [JohannesHeidecke/irl-benchmark#43]
Should contain new installation guide (without the SLM part for now). Also update requirements.txt.

Test on some other machine if installation guide contains all necessary steps.

**Comment by dit7ya** [comment]
# Introduction

`irl-benchmark` is a modular library for evaluating various Inverse Reinforcement Learning algorithms. It provides an extensible platform for experimenting with different environments, algorithms and metrics. 

# Installation

`pip install requirements.txt`

# Environemts

- FrozenLakev0
